version: '3'
services:
    couch-db:
        image: treehouses/rpi-couchdb:2.1.1
        ports:
            - "5984:5984"
        network_mode: "host"
        restart: always
        tty: true
    av-api:
        image: byuoitav/rpi-av-api:latest
        ports:
           - "8000:8000"
        environment:
            - BYPASS_AUTH=true
            - SYSTEM_ID=BLDG-ROOM-CP1
            - ROOM_SYSTEM=true
            - DB_ADDRESS=http://localhost:5984
            - HUB_ADDRESS=localhost:7100
            - STOP_REPLICATION=true
        network_mode: "host"
        restart: always
        tty: true
    touchpanel-ui-microservice:
        image: byuoitav/rpi-touchpanel-ui-microservice:latest
        ports:
            - "8888:8888"
        environment:
            - SYSTEM_ID=BLDG-ROOM-CP1
            - BYPASS_AUTH=true
            - ROOM_SYSTEM=true
            - DB_ADDRESS=http://localhost:5984
            - HUB_ADDRESS=localhost:7100
            - STOP_REPLICATION=true            
        network_mode: "host"
        restart: always
        tty: true
    adcp-control-microservice:
        image: byuoitav/rpi-adcp-control-microservice:latest
        ports:
            - "8012:8012"     
        environment:
            - SYSTEM_ID=BLDG-ROOM-CP1
            - BYPASS_AUTH=true
            - ROOM_SYSTEM=true               
        network_mode: "host"
        restart: always
        tty: true
    central-event-hub:
        image: byuoitav/rpi-central-event-hub:latest
        ports:
            - "7100:7100"
        environment:
            - SYSTEM_ID=BLDG-ROOM-CP1
            - BYPASS_AUTH=true
            - STOP_REPLICATION=true
        network_mode: "host"
        restart: always
        tty: true
