version: '3'
services:
    av-api:
        image: byuoitav/rpi-av-api:latest
        ports:
           - "8000:8000"
        environment:
            - BYPASS_AUTH=true
            - SYSTEM_ID=BLDG-ROOM-CP1
            - ROOM_SYSTEM=true
            - DB_ADDRESS=http://localhost:5984
            - STOP_REPLICATION=true
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
                mode: non-blocking
                max-buffer-size: 4m
    touchpanel-ui-microservice:
        image: byuoitav/rpi-touchpanel-ui-microservice:latest
        ports:
            - "8888:8888"
        environment:
            - SYSTEM_ID=BLDG-ROOM-CP1
            - ROOM_SYSTEM=true
            - DB_ADDRESS=http://localhost:5984
            - STOP_REPLICATION=true
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    adcp-control-microservice:
        image: byuoitav/rpi-adcp-control-microservice:latest
        ports:
            - "8012:8012"
        environment:
            - ROOM_SYSTEM=true
            - SYSTEM_ID=ITB-BLDG-ROOM-CP1
            - BYPASS_AUTH=true
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    couch-db:
        image: treehouses/rpi-couchdb:2.1.1
        ports:
            - "5984:5984"
        network_mode: "host"
        restart: always
        tty: true